## Numpy

In [1]:
import numpy as np

In [2]:
a_np=np.array([0,1,2,3,4])

In [3]:
type(a_np)

numpy.ndarray

In [15]:
a_np.dtype #returns data type of array

dtype('int32')

In [13]:
a_np[1]=2.3

ValueError: invalid literal for int() with base 10: 'adf'

In [14]:
a_np.size #returns size of array

5

In [16]:
a_np.ndim #returns dimesion of array

1

#### Two Dimesional Array

In [31]:
dm_array_np=np.array([[1,2],[3,4]])
print(dm_array_np.ndim)
print(dm_array_np.size)

2
4


In [32]:
u=[1,0]
v=[0,1]
z=[]
for n,m in zip(u,v): #zip is used to perform operations on 2 vectors element wise
    z.append(n+m)
print(z)

[1, 1]


In [33]:
#Vector addition
u=np.array([1,0])
v=np.array([0,1])
z=u+v
print(z)

[1 1]


In [34]:
#Vector subtraction
u=np.array([1,0])
v=np.array([0,1])
z=u-v
print(z)

[ 1 -1]


In [36]:
#Dot product
u=np.array([1,2])
v=np.array([3,2])
print(np.dot(u,v))

7


In [44]:
#Normal Multiplication
print(u*v)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim
b=a.flatten()

[3 4]


In [61]:
#Universal Functions
print(np.mean(a))
print(np.max(a))
print(np.pi)
print(a)
print(a[1:3,1:3]) #it means first argument is consern about row and second argument is consern about column
print(a[0:3,1]) 
#OR
print(a[:,1])
print(a[2,2])


5.0
9
3.141592653589793
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[2 5 8]
[2 5 8]
9


#### Some important Array construction functions

In [65]:
np.linspace(-2,2,num=10) #it is used to create sequence of array

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])